### ISSUE TITLE
Correções Slot Machine

### ISSUE THREAD

**Issue by gabrieltosta96** [robertorj7/slot-machine-heroway#1]
Aqui você poderia utilizar o `items.length` ao invés de `4`
https://github.com/robertorj7/slot-machine-heroway/blob/1e43c6885e90d7b1a9ad91fddd3cf9448bacdb29/scripts/index.js#L46

-----

Aqui você poderia utilizar o `items.length` ao invés de `4`
https://github.com/robertorj7/slot-machine-heroway/blob/1e43c6885e90d7b1a9ad91fddd3cf9448bacdb29/scripts/index.js#L58

-----

Mais relacionado a performance do que qualquer outra coisa:
Nesse caso como é um número aleatório, ao invés de buscar pelo `id` do heroi, você poderia pegar pelo `index` do array.length mesmo!
https://github.com/robertorj7/slot-machine-heroway/blob/1e43c6885e90d7b1a9ad91fddd3cf9448bacdb29/scripts/index.js#L48

Eu particularmente não gosto de colocar um `.reward` no final de um find. as vezes passa batido e a gente não enxerga o acesso ao atributo
Sempre que possível fazer da seguinte forma:
```js
    const item = items.find((item) => {
        return item.id === selectedId;
    });
    const reward = item.reward;
```
https://github.com/robertorj7/slot-machine-heroway/blob/1e43c6885e90d7b1a9ad91fddd3cf9448bacdb29/scripts/index.js#L72

Considerações finais:
Parabéns Roberto, ficou muito bom seu código. Todas as pontuações que eu fiz foram pontuações simples, nada critico.
Parabéns de verdade! ♥

**Comment by robertorj7** [comment]
Valeu pelas dicas de boas práticas.
Obrigado Gabriel!
